version: "3.5"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped

  covizu:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        basepath: .
        port: 8001
    container_name: covizu
    ports:
      - 8001:8001
    depends_on:
      - mongodb

  epicov:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        basepath: .
        port: 8003
    container_name: epicov
    ports:
      - 8003:8003

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres

volumes:
  postgres: