name: Pylint

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base
          echo "R_HOME=$(R RHOME)" >> "$GITHUB_ENV"
          echo "$(R RHOME)/bin" >> "$GITHUB_PATH"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint biopython rpy2 psycopg2-binary

      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=8 $(git ls-files '*.py') --rcfile=config/.pylintrc
